# Generated by Django 5.0.3 on 2024-04-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$EysXq5Mzl1nQwkvTmxL2Tc$fuc7piCF7qk67r45xchyd2rSuehLIi7cscPTOxcz4iI=', max_length=128),
        ),
    ]
