# Generated by Django 5.0.3 on 2024-04-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$wYrUlC4Z5ANZ2P1MHWbA8I$L8E39hzSq21rrex0JEbmINY1NRzCSUqGdy4jxhSBhCA=', max_length=128),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='ARBRE', max_length=150, unique=True),
        ),
    ]
