# Generated by Django 5.0.3 on 2024-04-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_customuser_password_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$CPGdqv6vtfI6i8d4DSRFvL$Jaqv/m2Amz4w5cBtFr2Tsqmzxt8tLb8VOyTjfS/MmL8=', max_length=128),
        ),
    ]
