# Generated by Django 5.0.4 on 2024-04-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_alter_colis_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colis',
            name='destination',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colis',
            name='expediteur',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colis',
            name='transporteur',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
