# Generated by Django 5.0.4 on 2024-04-07 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_auto_20240407_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='transporteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.transporteur'),
        ),
    ]
