# Generated by Django 5.0.2 on 2024-03-05 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_colis_destinataire_alter_colis_expediteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colis',
            name='destinataire',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.destinataire'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='expediteur',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.expediteur'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='numeroConfirmation',
            field=models.CharField(default=441223, max_length=6),
        ),
        migrations.AlterField(
            model_name='colis',
            name='vehicule',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.vehicle'),
        ),
    ]
