# Generated by Django 5.0.3 on 2024-04-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$720000$CBeTD654TJYBnCkG98yxKX$vy8NTI+nE68zavkUq10h7WOsqm8ckgggWkbOloofVN4=', max_length=128),
        ),
    ]
