# Generated by Django 5.0.3 on 2024-04-07 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colis',
            name='vehicule',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.vehicle'),
        ),
    ]
