# Generated by Django 5.0.4 on 2024-04-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_rename_numerosuivi_colis_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colis',
            name='expediteur',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='colis',
            name='transporteur',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
