# Generated by Django 5.0.4 on 2024-04-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_alter_colis_expediteur_alter_colis_transporteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colis',
            name='destination',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
