# Generated by Django 5.0.4 on 2024-04-07 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_alter_colis_destination_alter_colis_expediteur_and_more'),
    ]

    operations = [
    ]
