# Generated by Django 5.0.4 on 2024-04-07 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_alter_colis_transporteur_alter_vehicle_transporteur'),
    ]

    operations = [
    ]
